### ISSUE TITLE
can not download the dataset

### ISSUE THREAD

**Issue by Amo5** [hubert0527/infinityGAN#3]
I cannot download the datasets, could you please help me check whether there is a resource problem?

**Comment by hubert0527** [comment]
Which dataset? Both Flickr datasets look working fine to me.
The In&Out datasets have not been released, and will be released later via that paper.

**Comment by Amo5** [comment]
> 
Flickr datasets.
Maybe it's my Internet problem

**Comment by Amo5** [comment]
hi,
  Both Flickr datasets don't contain valid data?

**Comment by hubert0527** [comment]
No, current GANs do not have serious generalization issues yet, so using holdout set is unnecessary. The training and testing both happens on the training set. You can find a similar protocol in most GANs repo.

**Comment by Amo5** [comment]
OK, thanks for your reply。
